name: Build and push

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  push:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
        # Checkout code
      - name: Clone repository
        uses: actions/checkout@v2

      # Login to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push container
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/petterhj/ytdvr:latest
